language: php

php:
  - 5.6

sudo: false

cache:
  directories:
    - $HOME/.composer/cache


install:
  - travis_retry composer install --prefer-dist --optimize-autoloader --quiet

script:
  - vendor/bin/phpunit