language: php

php:
  - 5.6

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before-install:
  - composer self-update

install:
  - composer install --prefer-dist --optimize-autoloader --quiet

script:
  - vendor/bin/phpunit